name: GitHub Readme YouTube Cards
on:
  push:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCkFj-5ptpNAk3JDN4_vwiVQ
